#ifndef __definitions_H__
#define __definitions_H__

#include "config.h"

#define ARMYGUY_POS_X_MULTIPLY (ARMYGUY_POS_X_MARGIN+ARMYGUY_WIDTH)
#define ARMYGUY_POS_Y_MULTIPLY (ARMYGUY_POS_Y_MARGIN+ARMYGUY_HEIGHT)
#define ARMYGUY_LIMIT_RIGHT (ARMYGUY_POSLIMIT_RIGHT-ARMYGUY_WIDTH)
#define ARMYGUY_LIMIT_DOWN (ARMYGUY_POSLIMIT_DOWN-ARMYGUY_HEIGHT)
#define ARMYGUY_LIMIT_LEFT ARMYGUY_POSLIMIT_LEFT
#define ARMYGUY_LIMIT_UP ARMYGUY_POSLIMIT_UP
#define ARMYGUY_DIRECTION_LEFT 0
#define ARMYGUY_DIRECTION_RIGHT   1
#define ARMYGUY_ALIVE 0
#define ARMYGUY_DEAD 1
#define ARMYGUY_TYPE_0 0
#define ARMYGUY_TYPE_1 1
#define ARMYGUY_TYPE_2 2
#define ARMYGUY_TYPE_3 3
#define ARMYGUY_TYPE_4 4
#define ARMYGUY_TYPE_5 5

#define PLAYER_LIMIT_RIGHT (PLAYER_POSLIMIT_RIGHT-PLAYER_WIDTH)
#define PLAYER_LIMIT_DOWN (PLAYER_POSLIMIT_DOWN-PLAYER_HEIGHT)
#define PLAYER_LIMIT_LEFT PLAYER_POSLIMIT_LEFT
#define PLAYER_ALIVE 0
#define PLAYER_DEAD 1

#define PLAYERSHOT_NOTUSED 0
#define PLAYERSHOT_USED 1

#define ARMYSHOT_NOTUSED 0
#define ARMYSHOT_USED 1

#define EXPLOSION_NOTUSED 0
#define EXPLOSION_USED 1

#define COUNTERS 15
#define C_ARMYSHOTS_MOVE &counters[0]
#define C_PLAYER_MOVE &counters[1]
#define C_ARMYGUYS_ATTACK &counters[2]
#define C_ARMYGUYS_MOVE &counters[3]
#define C_PLAYERSHOTS_MOVE &counters[4]
#define C_PLAYER_ATTACK &counters[5]
#define C_WIN_LOSS &counters[6]

#define PLAYERSHOT_LIMIT_UP (PLAYERSHOT_POSLIMIT_UP-PLAYERSHOT_HEIGHT)

#define ARMYSHOT_LIMIT_DOWN (ARMYSHOT_POSLIMIT_DOWN-ARMYSHOT_HEIGHT)

#define SHIELD_LEFT 0
#define SHIELD_CENTER 1
#define SHIELD_RIGHT 2

#define SHIELD_ALIVE 0
#define SHIELD_DEAD 1

#define EXPLOSION_ANIM_LEN 7
#define ARMYGUY_ANIM_LEN 2

#define S_GAMEOVER 0 //
#define S_PLAYERSHOT 1 //
#define S_ARMYSHOT 2 //
#define S_PLAYEREXPLOSION 3 //
#define S_ARMYEXPLOSION 4 //
#define S_EXPLOSION 5 //
#define S_TIC 6 //
#define S_CONGRATULATIONS 7 //
#define S_ARMYDEATH 8 //
#define S_WELCOME 9 //


#define PLAYER_IMAGE obj0

#define ARMYGUY_IMAGE_1 obj1
#define ARMYGUY_IMAGE_2 obj3
#define ARMYGUY_IMAGE_3 obj5
#define ARMYGUY_IMAGE_4 obj7
#define ARMYGUY_IMAGE_5 obj9
#define ARMYGUY_IMAGE_6 obj11
#define ARMYGUY_IMAGE_7 obj13

#define PLAYERSHOT_IMAGE obj15

#define ARMYSHOT_IMAGE obj16

#define SHIELD_IMAGE_LEFT obj17
#define SHIELD_IMAGE_CENTER obj18
#define SHIELD_IMAGE_RIGHT obj19

#define EXPLOSION_IMAGE_1 obj20
#define EXPLOSION_IMAGE_2 obj24
#define EXPLOSION_IMAGE_3 obj28
#define EXPLOSION_IMAGE_4 obj32

#define SOUND_TIC tic_s
#define SOUND_TIC_LEN 5648 
#define SOUND_TIC_RATE 11025

#define SOUND_PLAYERSHOT playershot_s
#define SOUND_PLAYERSHOT_LEN 5488 
#define SOUND_PLAYERSHOT_RATE 11025

#define SOUND_ARMYSHOT armyshot_s
#define SOUND_ARMYSHOT_LEN 6144 
#define SOUND_ARMYSHOT_RATE 11025

#define SOUND_PLAYEREXPLOSION playerexplosion_s
#define SOUND_PLAYEREXPLOSION_LEN 10736 
#define SOUND_PLAYEREXPLOSION_RATE 11025

#define SOUND_ARMYEXPLOSION armyexplosion_s
#define SOUND_ARMYEXPLOSION_LEN 4512 
#define SOUND_ARMYEXPLOSION_RATE 11025

#define SOUND_EXPLOSION explosion_s
#define SOUND_EXPLOSION_LEN 2752
#define SOUND_EXPLOSION_RATE 11025

#define SOUND_GAMEOVER gameover_s
#define SOUND_GAMEOVER_LEN 11056
#define SOUND_GAMEOVER_RATE 11025

#define SOUND_CONGRATULATIONS congratulations_s
#define SOUND_CONGRATULATIONS_LEN 22080
#define SOUND_CONGRATULATIONS_RATE 11025

#define SOUND_WELCOME welcome_s
#define SOUND_WELCOME_LEN 22080 
#define SOUND_WELCOME_RATE 11025

#define SOUND_ARMYDEATH armydeath_s
#define SOUND_ARMYDEATH_LEN 4832
#define SOUND_ARMYDEATH_RATE 11025

#endif
